site_name: Programmation Zéro

copyright: "Copyright &copy; 2017 Haute école d'ingénierie et d'architecture de Fribourg"

pages:
    - Introduction: index.md
    - Installation: install.md
    - Bonjour le monde: hello_world.md
    - A propos: about.md


theme_dir: 'mkdocs-material/material'

markdown_extensions:
    - footnotes
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde

extra:
    palette:
        primary: 'blue'
        accent: 'orange'