site_name: Programmation Zéro

copyright: "Copyright &copy; 2017 Haute école d'ingénierie et d'architecture de Fribourg"

pages:
    - Introduction: index.md
    - Installation: install.md
    - Bonjour le monde: hello_world.md
    - Les nombres impairs: odd_numbers.md
    - La suite de Fibonacci: fibonacci.md
    - Les oeuvres d'art: art.md
    - Je cache un nombre et tu le devines: hide_a_number.md
    - La récursivité: recursivity.md
    - Facebook Sticker: facebook.md
    - Les éléments chimiques: elements.md

theme: 'material'

markdown_extensions:
    - footnotes
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
#   - mdx_math

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
    palette:
        primary: 'blue'
        accent: 'orange'