site_name: Programmation Zéro
site_description: Cours d'introduction à la programmation pour les étudiants de la HEIA-FR
copyright: "Copyright &copy; 2020 Haute école d'ingénierie et d'architecture de Fribourg"
site_url: https://programmation-zero.tic.heia-fr.ch/
google_analytics: ['UA-124597956-1', 'auto']

nav:
  - Introduction: index.md
  - Installation: install.md
  - Bonjour le monde: hello_world.md
  - Les nombres impairs: odd_numbers.md
  - La suite de Fibonacci: fibonacci.md
  - L'arrondi à 5 centimes: five_cents.md
  - Les sommes de contrôle: checksum.md
  - Les tours de Hanoï: hanoi.md
  - Les nombres à l'envers: reverse.md
  - Le PGCD: euclid.md
  - Les bases 2 et 10: bases.md
  - Les œuvres d'art: art.md
  - Les nombres premiers: primes.md
  - Les palindromes: palindromes.md
  - Je cache un nombre et tu le devines: hide_a_number.md
  #    - Tu caches un nombre et je le devine: guess_a_number.md
  - La récursivité: recursivity.md
  - Compter les lettres: letter_count.md
  - Facebook Sticker: facebook.md
  - Les éléments chimiques: elements.md
  - Besoin de plus d'argent ?: more_money.md
  - Données: data.md
  - Ressources supplémentaires: resources.md

theme: 'material'

markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
#  - mdx_math

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  palette:
    primary: 'blue'
    accent: 'orange'
